name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.2.2
        with:
          linter: jetbrains/qodana-<linter>
